name: Docker Image CI

on:
  push:
    tags:
      - "**"             # Push events to v1 tag

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        id: publish
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: hjin/es-ik
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
